# @package hydra.launcher # default
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.LocalLauncher # default
submitit_folder: ${hydra.sweep.dir}/.submitit/%j # default
timeout_min: 60 # default
cpus_per_task: 1 # default
gpus_per_node: 0 # default
tasks_per_node: 1 # default
mem_gb: 4 # default
nodes: 1 # default
name: ${hydra.job.name} # default
