# @package hydra.launcher    # default
submitit_folder: ${hydra.sweep.dir}/.submitit/%j    # default
timeout_min: 60    # default
cpus_per_task: null    # default
gpus_per_node: null    # default
tasks_per_node: 1    # default
mem_gb: null    # default
nodes: 1    # default
name: ${hydra.job.name}    # default
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher    # default
partition: null    # default
qos: null    # default
comment: null    # default
constraint: null    # default
exclude: null    # default
gres: null    # default
cpus_per_gpu: null    # default
gpus_per_task: null    # default
mem_per_gpu: null    # default
mem_per_cpu: null    # default
account: null    # default
signal_delay_s: 120    # default
max_num_timeout: 0    # default
additional_parameters: {}    # default
array_parallelism: 256    # default
setup: null    # default
srun_args: null    # default
